# Generated by Django 5.1.4 on 2025-01-28 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='cars/')),
                ('year', models.PositiveIntegerField(default=2024)),
                ('gearbox', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic')], default='manual', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='Diesel', max_length=20)),
                ('passenger', models.PositiveIntegerField(default=5)),
                ('description', models.CharField(max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(default='TANGER ', max_length=100)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('identity_card_image', models.ImageField(blank=True, null=True, upload_to='clients/identity_cards/')),
                ('driver_license_image', models.ImageField(blank=True, null=True, upload_to='clients/driver_licenses/')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='clients/passports/')),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Rating of the client (1 to 5)')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(default='TANGER ', max_length=100)),
                ('identity_card_image', models.ImageField(blank=True, null=True, upload_to='clients/identity_cards/')),
                ('driver_license_image', models.ImageField(blank=True, null=True, upload_to='clients/driver_licenses/')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='clients/passports/')),
            ],
        ),
        migrations.CreateModel(
            name='CarExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='rent.car')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pdf_receipt', models.FileField(blank=True, null=True, upload_to='reservations/pdfs/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rent.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rent.client')),
                ('drivers', models.ManyToManyField(blank=True, related_name='reservations', to='rent.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rent.reservation')),
            ],
        ),
    ]
