# Generated by Django 5.1.4 on 2025-02-02 17:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Brand')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Registration Plate')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Image')),
                ('year', models.PositiveIntegerField(default=2024, verbose_name='Year')),
                ('gearbox', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic')], default='manual', max_length=20, verbose_name='Transmission')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='Diesel', max_length=20, verbose_name='Fuel Type')),
                ('number_of_passengers', models.PositiveIntegerField(default=5, verbose_name='Number of passengers')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=300, max_digits=10, verbose_name='Daily Rate')),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Expenditure')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')], verbose_name='Phone Number')),
                ('address', models.CharField(default='TANGER', max_length=100, verbose_name='Address')),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount Paid')),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount Due')),
                ('identity_card_front', models.ImageField(blank=True, null=True, upload_to='clients/identity_cards/fronts/', verbose_name='Identity Card Front')),
                ('identity_card_back', models.ImageField(blank=True, null=True, upload_to='clients/identity_cards/backs/', verbose_name='Identity Card Back')),
                ('driver_license_front', models.ImageField(blank=True, null=True, upload_to='clients/driver_licenses/fronts/', verbose_name='Driver License Front')),
                ('driver_license_back', models.ImageField(blank=True, null=True, upload_to='clients/driver_licenses/backs/', verbose_name='Driver License Back')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='clients/passports/', verbose_name='Passport Image')),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Rating of the client (1 to 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Client Rating')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')], verbose_name='Phone Number')),
                ('address', models.CharField(default='Tanger', max_length=100, verbose_name='Address')),
                ('identity_card_front', models.ImageField(blank=True, null=True, upload_to='drivers/identity_cards/fronts/', verbose_name='Identity Card Front')),
                ('identity_card_back', models.ImageField(blank=True, null=True, upload_to='drivers/identity_cards/backs/', verbose_name='Identity Card Back')),
                ('driver_license_front', models.ImageField(blank=True, null=True, upload_to='drivers/driver_licenses/fronts/', verbose_name='Driver License Front')),
                ('driver_license_back', models.ImageField(blank=True, null=True, upload_to='drivers/driver_licenses/backs/', verbose_name='Driver License Back')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='drivers/passports/', verbose_name='Passport Image')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='ExpenditureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Expenditure Type',
                'verbose_name_plural': 'Expenditures Types',
            },
        ),
        migrations.CreateModel(
            name='CarExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='rent.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Car Expenditure',
                'verbose_name_plural': 'Car Expenditures',
            },
        ),
        migrations.CreateModel(
            name='BusinessExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BusinessExpenditures', to='rent.expendituretype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Business Expenditure',
                'verbose_name_plural': 'Business Expenditures',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Total Cost')),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20, verbose_name='Payment Status')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Paid')),
                ('pdf_receipt', models.FileField(blank=True, null=True, upload_to='reservations/pdfs/', verbose_name='PDF Receipt')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rent.car', verbose_name='Car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rent.client', verbose_name='Client')),
                ('drivers', models.ManyToManyField(blank=True, related_name='reservations', to='rent.driver', verbose_name='Drivers')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Paid')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rent.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
