# Generated by Django 5.1.4 on 2025-01-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pdf_receipt',
            field=models.FileField(blank=True, null=True, upload_to='reservations/pdfs/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='Diesel', max_length=20),
        ),
    ]
