# Generated by Django 5.1.4 on 2024-12-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-Automatic')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='passenger',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
