# Generated by Django 5.1.4 on 2025-02-03 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expendituretype',
            options={'verbose_name': 'Expenditures Type', 'verbose_name_plural': 'Expenditures Types'},
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='client',
            name='driver_license_number',
            field=models.CharField(default='qws1234', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]+$', 'Enter a valid driver’s license number.')], verbose_name="Driver's License Number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='identity_card_number',
            field=models.CharField(default='asd', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]+$', 'Enter a valid ID card number.')], verbose_name='Identity Card Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_license_number',
            field=models.CharField(default='aqw', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]+$', 'Enter a valid driver’s license number.')], verbose_name="Driver's License Number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='identity_card_number',
            field=models.CharField(default='123', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]+$', 'Enter a valid ID card number.')], verbose_name='Identity Card Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
    ]
