# Generated by Django 5.1.4 on 2024-12-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_car_fuel_type_car_gearbox_car_passenger_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='prix',
            field=models.PositiveIntegerField(default=250),
        ),
    ]
