# Generated by Django 5.1.4 on 2025-02-03 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_expendituretype_options_client_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dropoff_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Dropoff Time'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Pickup Time'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
    ]
