# Generated by Django 5.1.4 on 2025-02-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_reservation_dropoff_time_reservation_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
