# Generated by Django 5.1.4 on 2025-02-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_car_is_available_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='actual_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Actual Daily Rate'),
        ),
    ]
