# Generated by Django 5.1.4 on 2025-02-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_reservation_actual_daily_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
